version: '2.1'
volumes:
  db_data:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - database
    volumes:
      - ./:/app
    ports:
      - '5000:8080'
    env_file:
      - .env
    command: >
      ash -c "php artisan migrate
      && php -S 0.0.0.0:8080 -t public"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: gnwfdwwo
      DB_USERNAME: gnwfdwwo
      DB_PASSWORD: D87o95IHOzY1zJMaDGGPGsGiVg6kOO-O
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:9.6-alpine
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gnwfdwwo
      POSTGRES_PASSWORD: D87o95IHOzY1zJMaDGGPGsGiVg6kOO-O
      POSTGRES_DB: gnwfdwwo
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U gnwfdwwo']
      interval: 5s
      timeout: 10s
      retries: 5
  